Allow a popup page as the download page
gowithfloat/Float.TinCan.ActivityLibrary pull request #23
Opened 2022-07-21 17:07 UTC by EBusch

2022-07-22 01:44 UTC, mediabounds requested changes

2022-07-22 01:44 UTC, mediabounds commented on Float.TinCan.ActivityLibrary/ActivityLaunchCoordinator.cs
> +using Rg.Plugins.Popup.Services;
@EBusch Ideally we would avoid adding new dependencies to this library. We can do that by creating new overridable methods for handling presenting and dismissing of the downloading page.

2022-07-22 01:44 UTC, mediabounds commented on Float.TinCan.ActivityLibrary/ActivityLaunchCoordinator.cs
> +                    }
@EBusch ActivityLibrary doesn't need to care about the type of page -- we can instead do something like this:
```
ShowDownloadStatus(CreateDownloadStatusPage(downloadStatus));
```

And define this method:
```
protected virtual void ShowDownloadStatus(ContentPage downloadStatusPage)
{
  NavigationContext.PresentPage(downloadStatusPage);
}
```

Now the child class can override that method and decide how to show the page.

2022-07-22 01:44 UTC, mediabounds commented on Float.TinCan.ActivityLibrary/ActivityLaunchCoordinator.cs
> +                }
@EBusch Similarly, we can do something like this here:
```
await HideDownloadStatus();
...
protected virtual Task HideDownloadStatus()
{
  return NavigationContext.PopPageAsync();
}
```

2022-07-25 16:08 UTC, bbeversdorf approved these changes
In general, this looks(?) pretty safe. It will need a thorough run thru though.

2022-07-25 16:08 UTC, bbeversdorf commented on Float.TinCan.ActivityLibrary/ActivityLaunchCoordinator.cs
> +                    await ShowDownloadStatus(CreateDownloadStatusPage(downloadStatus));
@EBusch Could we get into a state where we are creating/presenting the download page more than once?
_just wondering if we need a protection from creating multiple_

2022-07-25 16:12 UTC, merged